/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FreeQuoteRouteImport } from './routes/free-quote'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ServicesInGroundPrefabricatedStormSheltersRouteImport } from './routes/services/in-ground-prefabricated-storm-shelters'
import { Route as ServicesCustomBuiltStormSheltersRouteImport } from './routes/services/custom-built-storm-shelters'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeQuoteRoute = FreeQuoteRouteImport.update({
  id: '/free-quote',
  path: '/free-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInGroundPrefabricatedStormSheltersRoute =
  ServicesInGroundPrefabricatedStormSheltersRouteImport.update({
    id: '/in-ground-prefabricated-storm-shelters',
    path: '/in-ground-prefabricated-storm-shelters',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCustomBuiltStormSheltersRoute =
  ServicesCustomBuiltStormSheltersRouteImport.update({
    id: '/custom-built-storm-shelters',
    path: '/custom-built-storm-shelters',
    getParentRoute: () => ServicesRoute,
  } as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/custom-built-storm-shelters': typeof ServicesCustomBuiltStormSheltersRoute
  '/services/in-ground-prefabricated-storm-shelters': typeof ServicesInGroundPrefabricatedStormSheltersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/custom-built-storm-shelters': typeof ServicesCustomBuiltStormSheltersRoute
  '/services/in-ground-prefabricated-storm-shelters': typeof ServicesInGroundPrefabricatedStormSheltersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/services/custom-built-storm-shelters': typeof ServicesCustomBuiltStormSheltersRoute
  '/services/in-ground-prefabricated-storm-shelters': typeof ServicesInGroundPrefabricatedStormSheltersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/custom-built-storm-shelters'
    | '/services/in-ground-prefabricated-storm-shelters'
    | '/dashboard/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/custom-built-storm-shelters'
    | '/services/in-ground-prefabricated-storm-shelters'
    | '/dashboard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/services/custom-built-storm-shelters'
    | '/services/in-ground-prefabricated-storm-shelters'
    | '/dashboard/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FreeQuoteRoute: typeof FreeQuoteRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-quote': {
      id: '/free-quote'
      path: '/free-quote'
      fullPath: '/free-quote'
      preLoaderRoute: typeof FreeQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/in-ground-prefabricated-storm-shelters': {
      id: '/services/in-ground-prefabricated-storm-shelters'
      path: '/in-ground-prefabricated-storm-shelters'
      fullPath: '/services/in-ground-prefabricated-storm-shelters'
      preLoaderRoute: typeof ServicesInGroundPrefabricatedStormSheltersRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-built-storm-shelters': {
      id: '/services/custom-built-storm-shelters'
      path: '/custom-built-storm-shelters'
      fullPath: '/services/custom-built-storm-shelters'
      preLoaderRoute: typeof ServicesCustomBuiltStormSheltersRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCustomBuiltStormSheltersRoute: typeof ServicesCustomBuiltStormSheltersRoute
  ServicesInGroundPrefabricatedStormSheltersRoute: typeof ServicesInGroundPrefabricatedStormSheltersRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCustomBuiltStormSheltersRoute: ServicesCustomBuiltStormSheltersRoute,
  ServicesInGroundPrefabricatedStormSheltersRoute:
    ServicesInGroundPrefabricatedStormSheltersRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FreeQuoteRoute: FreeQuoteRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
