/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FreeQuoteRouteImport } from './routes/free-quote'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ServicesTreeBrushRemovalRouteImport } from './routes/services/tree-brush-removal'
import { Route as ServicesResidentialWireHouseCleaningRouteImport } from './routes/services/residential-wire-house-cleaning'
import { Route as ServicesOfficeCommercialCleaningRouteImport } from './routes/services/office-commercial-cleaning'
import { Route as ServicesLawnMowingRouteImport } from './routes/services/lawn-mowing'
import { Route as ServicesLandscapingRouteImport } from './routes/services/landscaping'
import { Route as ServicesInGroundPrefabricatedStormSheltersRouteImport } from './routes/services/in-ground-prefabricated-storm-shelters'
import { Route as ServicesGravelDirtWorkRouteImport } from './routes/services/gravel-dirt-work'
import { Route as ServicesCustomBuiltStormSheltersRouteImport } from './routes/services/custom-built-storm-shelters'
import { Route as ServiceAreasWestMemphisArRouteImport } from './routes/service-areas/west-memphis-ar'
import { Route as ServiceAreasWallsMsRouteImport } from './routes/service-areas/walls-ms'
import { Route as ServiceAreasSouthavenMsRouteImport } from './routes/service-areas/southaven-ms'
import { Route as ServiceAreasOliveBranchMsRouteImport } from './routes/service-areas/olive-branch-ms'
import { Route as ServiceAreasNesbitMsRouteImport } from './routes/service-areas/nesbit-ms'
import { Route as ServiceAreasMemphisTnRouteImport } from './routes/service-areas/memphis-tn'
import { Route as ServiceAreasHornLakeMsRouteImport } from './routes/service-areas/horn-lake-ms'
import { Route as ServiceAreasHernandoMsRouteImport } from './routes/service-areas/hernando-ms'
import { Route as ServiceAreasGermantownTnRouteImport } from './routes/service-areas/germantown-tn'
import { Route as ServiceAreasCordovaTnRouteImport } from './routes/service-areas/cordova-tn'
import { Route as ServiceAreasColliervilleTnRouteImport } from './routes/service-areas/collierville-tn'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeQuoteRoute = FreeQuoteRouteImport.update({
  id: '/free-quote',
  path: '/free-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTreeBrushRemovalRoute =
  ServicesTreeBrushRemovalRouteImport.update({
    id: '/tree-brush-removal',
    path: '/tree-brush-removal',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesResidentialWireHouseCleaningRoute =
  ServicesResidentialWireHouseCleaningRouteImport.update({
    id: '/residential-wire-house-cleaning',
    path: '/residential-wire-house-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesOfficeCommercialCleaningRoute =
  ServicesOfficeCommercialCleaningRouteImport.update({
    id: '/office-commercial-cleaning',
    path: '/office-commercial-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLawnMowingRoute = ServicesLawnMowingRouteImport.update({
  id: '/lawn-mowing',
  path: '/lawn-mowing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLandscapingRoute = ServicesLandscapingRouteImport.update({
  id: '/landscaping',
  path: '/landscaping',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInGroundPrefabricatedStormSheltersRoute =
  ServicesInGroundPrefabricatedStormSheltersRouteImport.update({
    id: '/in-ground-prefabricated-storm-shelters',
    path: '/in-ground-prefabricated-storm-shelters',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesGravelDirtWorkRoute = ServicesGravelDirtWorkRouteImport.update({
  id: '/gravel-dirt-work',
  path: '/gravel-dirt-work',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomBuiltStormSheltersRoute =
  ServicesCustomBuiltStormSheltersRouteImport.update({
    id: '/custom-built-storm-shelters',
    path: '/custom-built-storm-shelters',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServiceAreasWestMemphisArRoute =
  ServiceAreasWestMemphisArRouteImport.update({
    id: '/west-memphis-ar',
    path: '/west-memphis-ar',
    getParentRoute: () => ServiceAreasRoute,
  } as any)
const ServiceAreasWallsMsRoute = ServiceAreasWallsMsRouteImport.update({
  id: '/walls-ms',
  path: '/walls-ms',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasSouthavenMsRoute = ServiceAreasSouthavenMsRouteImport.update({
  id: '/southaven-ms',
  path: '/southaven-ms',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasOliveBranchMsRoute =
  ServiceAreasOliveBranchMsRouteImport.update({
    id: '/olive-branch-ms',
    path: '/olive-branch-ms',
    getParentRoute: () => ServiceAreasRoute,
  } as any)
const ServiceAreasNesbitMsRoute = ServiceAreasNesbitMsRouteImport.update({
  id: '/nesbit-ms',
  path: '/nesbit-ms',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasMemphisTnRoute = ServiceAreasMemphisTnRouteImport.update({
  id: '/memphis-tn',
  path: '/memphis-tn',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasHornLakeMsRoute = ServiceAreasHornLakeMsRouteImport.update({
  id: '/horn-lake-ms',
  path: '/horn-lake-ms',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasHernandoMsRoute = ServiceAreasHernandoMsRouteImport.update({
  id: '/hernando-ms',
  path: '/hernando-ms',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasGermantownTnRoute =
  ServiceAreasGermantownTnRouteImport.update({
    id: '/germantown-tn',
    path: '/germantown-tn',
    getParentRoute: () => ServiceAreasRoute,
  } as any)
const ServiceAreasCordovaTnRoute = ServiceAreasCordovaTnRouteImport.update({
  id: '/cordova-tn',
  path: '/cordova-tn',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasColliervilleTnRoute =
  ServiceAreasColliervilleTnRouteImport.update({
    id: '/collierville-tn',
    path: '/collierville-tn',
    getParentRoute: () => ServiceAreasRoute,
  } as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/service-areas/collierville-tn': typeof ServiceAreasColliervilleTnRoute
  '/service-areas/cordova-tn': typeof ServiceAreasCordovaTnRoute
  '/service-areas/germantown-tn': typeof ServiceAreasGermantownTnRoute
  '/service-areas/hernando-ms': typeof ServiceAreasHernandoMsRoute
  '/service-areas/horn-lake-ms': typeof ServiceAreasHornLakeMsRoute
  '/service-areas/memphis-tn': typeof ServiceAreasMemphisTnRoute
  '/service-areas/nesbit-ms': typeof ServiceAreasNesbitMsRoute
  '/service-areas/olive-branch-ms': typeof ServiceAreasOliveBranchMsRoute
  '/service-areas/southaven-ms': typeof ServiceAreasSouthavenMsRoute
  '/service-areas/walls-ms': typeof ServiceAreasWallsMsRoute
  '/service-areas/west-memphis-ar': typeof ServiceAreasWestMemphisArRoute
  '/services/custom-built-storm-shelters': typeof ServicesCustomBuiltStormSheltersRoute
  '/services/gravel-dirt-work': typeof ServicesGravelDirtWorkRoute
  '/services/in-ground-prefabricated-storm-shelters': typeof ServicesInGroundPrefabricatedStormSheltersRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/lawn-mowing': typeof ServicesLawnMowingRoute
  '/services/office-commercial-cleaning': typeof ServicesOfficeCommercialCleaningRoute
  '/services/residential-wire-house-cleaning': typeof ServicesResidentialWireHouseCleaningRoute
  '/services/tree-brush-removal': typeof ServicesTreeBrushRemovalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/service-areas/collierville-tn': typeof ServiceAreasColliervilleTnRoute
  '/service-areas/cordova-tn': typeof ServiceAreasCordovaTnRoute
  '/service-areas/germantown-tn': typeof ServiceAreasGermantownTnRoute
  '/service-areas/hernando-ms': typeof ServiceAreasHernandoMsRoute
  '/service-areas/horn-lake-ms': typeof ServiceAreasHornLakeMsRoute
  '/service-areas/memphis-tn': typeof ServiceAreasMemphisTnRoute
  '/service-areas/nesbit-ms': typeof ServiceAreasNesbitMsRoute
  '/service-areas/olive-branch-ms': typeof ServiceAreasOliveBranchMsRoute
  '/service-areas/southaven-ms': typeof ServiceAreasSouthavenMsRoute
  '/service-areas/walls-ms': typeof ServiceAreasWallsMsRoute
  '/service-areas/west-memphis-ar': typeof ServiceAreasWestMemphisArRoute
  '/services/custom-built-storm-shelters': typeof ServicesCustomBuiltStormSheltersRoute
  '/services/gravel-dirt-work': typeof ServicesGravelDirtWorkRoute
  '/services/in-ground-prefabricated-storm-shelters': typeof ServicesInGroundPrefabricatedStormSheltersRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/lawn-mowing': typeof ServicesLawnMowingRoute
  '/services/office-commercial-cleaning': typeof ServicesOfficeCommercialCleaningRoute
  '/services/residential-wire-house-cleaning': typeof ServicesResidentialWireHouseCleaningRoute
  '/services/tree-brush-removal': typeof ServicesTreeBrushRemovalRoute
  '/dashboard': typeof DashboardIndexRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/free-quote': typeof FreeQuoteRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/service-areas/collierville-tn': typeof ServiceAreasColliervilleTnRoute
  '/service-areas/cordova-tn': typeof ServiceAreasCordovaTnRoute
  '/service-areas/germantown-tn': typeof ServiceAreasGermantownTnRoute
  '/service-areas/hernando-ms': typeof ServiceAreasHernandoMsRoute
  '/service-areas/horn-lake-ms': typeof ServiceAreasHornLakeMsRoute
  '/service-areas/memphis-tn': typeof ServiceAreasMemphisTnRoute
  '/service-areas/nesbit-ms': typeof ServiceAreasNesbitMsRoute
  '/service-areas/olive-branch-ms': typeof ServiceAreasOliveBranchMsRoute
  '/service-areas/southaven-ms': typeof ServiceAreasSouthavenMsRoute
  '/service-areas/walls-ms': typeof ServiceAreasWallsMsRoute
  '/service-areas/west-memphis-ar': typeof ServiceAreasWestMemphisArRoute
  '/services/custom-built-storm-shelters': typeof ServicesCustomBuiltStormSheltersRoute
  '/services/gravel-dirt-work': typeof ServicesGravelDirtWorkRoute
  '/services/in-ground-prefabricated-storm-shelters': typeof ServicesInGroundPrefabricatedStormSheltersRoute
  '/services/landscaping': typeof ServicesLandscapingRoute
  '/services/lawn-mowing': typeof ServicesLawnMowingRoute
  '/services/office-commercial-cleaning': typeof ServicesOfficeCommercialCleaningRoute
  '/services/residential-wire-house-cleaning': typeof ServicesResidentialWireHouseCleaningRoute
  '/services/tree-brush-removal': typeof ServicesTreeBrushRemovalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/service-areas/collierville-tn'
    | '/service-areas/cordova-tn'
    | '/service-areas/germantown-tn'
    | '/service-areas/hernando-ms'
    | '/service-areas/horn-lake-ms'
    | '/service-areas/memphis-tn'
    | '/service-areas/nesbit-ms'
    | '/service-areas/olive-branch-ms'
    | '/service-areas/southaven-ms'
    | '/service-areas/walls-ms'
    | '/service-areas/west-memphis-ar'
    | '/services/custom-built-storm-shelters'
    | '/services/gravel-dirt-work'
    | '/services/in-ground-prefabricated-storm-shelters'
    | '/services/landscaping'
    | '/services/lawn-mowing'
    | '/services/office-commercial-cleaning'
    | '/services/residential-wire-house-cleaning'
    | '/services/tree-brush-removal'
    | '/dashboard/'
    | '/service-areas/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/service-areas/collierville-tn'
    | '/service-areas/cordova-tn'
    | '/service-areas/germantown-tn'
    | '/service-areas/hernando-ms'
    | '/service-areas/horn-lake-ms'
    | '/service-areas/memphis-tn'
    | '/service-areas/nesbit-ms'
    | '/service-areas/olive-branch-ms'
    | '/service-areas/southaven-ms'
    | '/service-areas/walls-ms'
    | '/service-areas/west-memphis-ar'
    | '/services/custom-built-storm-shelters'
    | '/services/gravel-dirt-work'
    | '/services/in-ground-prefabricated-storm-shelters'
    | '/services/landscaping'
    | '/services/lawn-mowing'
    | '/services/office-commercial-cleaning'
    | '/services/residential-wire-house-cleaning'
    | '/services/tree-brush-removal'
    | '/dashboard'
    | '/service-areas'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/free-quote'
    | '/projects'
    | '/reviews'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/login'
    | '/service-areas/collierville-tn'
    | '/service-areas/cordova-tn'
    | '/service-areas/germantown-tn'
    | '/service-areas/hernando-ms'
    | '/service-areas/horn-lake-ms'
    | '/service-areas/memphis-tn'
    | '/service-areas/nesbit-ms'
    | '/service-areas/olive-branch-ms'
    | '/service-areas/southaven-ms'
    | '/service-areas/walls-ms'
    | '/service-areas/west-memphis-ar'
    | '/services/custom-built-storm-shelters'
    | '/services/gravel-dirt-work'
    | '/services/in-ground-prefabricated-storm-shelters'
    | '/services/landscaping'
    | '/services/lawn-mowing'
    | '/services/office-commercial-cleaning'
    | '/services/residential-wire-house-cleaning'
    | '/services/tree-brush-removal'
    | '/dashboard/'
    | '/service-areas/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FreeQuoteRoute: typeof FreeQuoteRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-quote': {
      id: '/free-quote'
      path: '/free-quote'
      fullPath: '/free-quote'
      preLoaderRoute: typeof FreeQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tree-brush-removal': {
      id: '/services/tree-brush-removal'
      path: '/tree-brush-removal'
      fullPath: '/services/tree-brush-removal'
      preLoaderRoute: typeof ServicesTreeBrushRemovalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential-wire-house-cleaning': {
      id: '/services/residential-wire-house-cleaning'
      path: '/residential-wire-house-cleaning'
      fullPath: '/services/residential-wire-house-cleaning'
      preLoaderRoute: typeof ServicesResidentialWireHouseCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/office-commercial-cleaning': {
      id: '/services/office-commercial-cleaning'
      path: '/office-commercial-cleaning'
      fullPath: '/services/office-commercial-cleaning'
      preLoaderRoute: typeof ServicesOfficeCommercialCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/lawn-mowing': {
      id: '/services/lawn-mowing'
      path: '/lawn-mowing'
      fullPath: '/services/lawn-mowing'
      preLoaderRoute: typeof ServicesLawnMowingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/landscaping': {
      id: '/services/landscaping'
      path: '/landscaping'
      fullPath: '/services/landscaping'
      preLoaderRoute: typeof ServicesLandscapingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/in-ground-prefabricated-storm-shelters': {
      id: '/services/in-ground-prefabricated-storm-shelters'
      path: '/in-ground-prefabricated-storm-shelters'
      fullPath: '/services/in-ground-prefabricated-storm-shelters'
      preLoaderRoute: typeof ServicesInGroundPrefabricatedStormSheltersRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/gravel-dirt-work': {
      id: '/services/gravel-dirt-work'
      path: '/gravel-dirt-work'
      fullPath: '/services/gravel-dirt-work'
      preLoaderRoute: typeof ServicesGravelDirtWorkRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-built-storm-shelters': {
      id: '/services/custom-built-storm-shelters'
      path: '/custom-built-storm-shelters'
      fullPath: '/services/custom-built-storm-shelters'
      preLoaderRoute: typeof ServicesCustomBuiltStormSheltersRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/service-areas/west-memphis-ar': {
      id: '/service-areas/west-memphis-ar'
      path: '/west-memphis-ar'
      fullPath: '/service-areas/west-memphis-ar'
      preLoaderRoute: typeof ServiceAreasWestMemphisArRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/walls-ms': {
      id: '/service-areas/walls-ms'
      path: '/walls-ms'
      fullPath: '/service-areas/walls-ms'
      preLoaderRoute: typeof ServiceAreasWallsMsRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/southaven-ms': {
      id: '/service-areas/southaven-ms'
      path: '/southaven-ms'
      fullPath: '/service-areas/southaven-ms'
      preLoaderRoute: typeof ServiceAreasSouthavenMsRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/olive-branch-ms': {
      id: '/service-areas/olive-branch-ms'
      path: '/olive-branch-ms'
      fullPath: '/service-areas/olive-branch-ms'
      preLoaderRoute: typeof ServiceAreasOliveBranchMsRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/nesbit-ms': {
      id: '/service-areas/nesbit-ms'
      path: '/nesbit-ms'
      fullPath: '/service-areas/nesbit-ms'
      preLoaderRoute: typeof ServiceAreasNesbitMsRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/memphis-tn': {
      id: '/service-areas/memphis-tn'
      path: '/memphis-tn'
      fullPath: '/service-areas/memphis-tn'
      preLoaderRoute: typeof ServiceAreasMemphisTnRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/horn-lake-ms': {
      id: '/service-areas/horn-lake-ms'
      path: '/horn-lake-ms'
      fullPath: '/service-areas/horn-lake-ms'
      preLoaderRoute: typeof ServiceAreasHornLakeMsRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/hernando-ms': {
      id: '/service-areas/hernando-ms'
      path: '/hernando-ms'
      fullPath: '/service-areas/hernando-ms'
      preLoaderRoute: typeof ServiceAreasHernandoMsRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/germantown-tn': {
      id: '/service-areas/germantown-tn'
      path: '/germantown-tn'
      fullPath: '/service-areas/germantown-tn'
      preLoaderRoute: typeof ServiceAreasGermantownTnRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/cordova-tn': {
      id: '/service-areas/cordova-tn'
      path: '/cordova-tn'
      fullPath: '/service-areas/cordova-tn'
      preLoaderRoute: typeof ServiceAreasCordovaTnRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/collierville-tn': {
      id: '/service-areas/collierville-tn'
      path: '/collierville-tn'
      fullPath: '/service-areas/collierville-tn'
      preLoaderRoute: typeof ServiceAreasColliervilleTnRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServiceAreasRouteChildren {
  ServiceAreasColliervilleTnRoute: typeof ServiceAreasColliervilleTnRoute
  ServiceAreasCordovaTnRoute: typeof ServiceAreasCordovaTnRoute
  ServiceAreasGermantownTnRoute: typeof ServiceAreasGermantownTnRoute
  ServiceAreasHernandoMsRoute: typeof ServiceAreasHernandoMsRoute
  ServiceAreasHornLakeMsRoute: typeof ServiceAreasHornLakeMsRoute
  ServiceAreasMemphisTnRoute: typeof ServiceAreasMemphisTnRoute
  ServiceAreasNesbitMsRoute: typeof ServiceAreasNesbitMsRoute
  ServiceAreasOliveBranchMsRoute: typeof ServiceAreasOliveBranchMsRoute
  ServiceAreasSouthavenMsRoute: typeof ServiceAreasSouthavenMsRoute
  ServiceAreasWallsMsRoute: typeof ServiceAreasWallsMsRoute
  ServiceAreasWestMemphisArRoute: typeof ServiceAreasWestMemphisArRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasColliervilleTnRoute: ServiceAreasColliervilleTnRoute,
  ServiceAreasCordovaTnRoute: ServiceAreasCordovaTnRoute,
  ServiceAreasGermantownTnRoute: ServiceAreasGermantownTnRoute,
  ServiceAreasHernandoMsRoute: ServiceAreasHernandoMsRoute,
  ServiceAreasHornLakeMsRoute: ServiceAreasHornLakeMsRoute,
  ServiceAreasMemphisTnRoute: ServiceAreasMemphisTnRoute,
  ServiceAreasNesbitMsRoute: ServiceAreasNesbitMsRoute,
  ServiceAreasOliveBranchMsRoute: ServiceAreasOliveBranchMsRoute,
  ServiceAreasSouthavenMsRoute: ServiceAreasSouthavenMsRoute,
  ServiceAreasWallsMsRoute: ServiceAreasWallsMsRoute,
  ServiceAreasWestMemphisArRoute: ServiceAreasWestMemphisArRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

interface ServicesRouteChildren {
  ServicesCustomBuiltStormSheltersRoute: typeof ServicesCustomBuiltStormSheltersRoute
  ServicesGravelDirtWorkRoute: typeof ServicesGravelDirtWorkRoute
  ServicesInGroundPrefabricatedStormSheltersRoute: typeof ServicesInGroundPrefabricatedStormSheltersRoute
  ServicesLandscapingRoute: typeof ServicesLandscapingRoute
  ServicesLawnMowingRoute: typeof ServicesLawnMowingRoute
  ServicesOfficeCommercialCleaningRoute: typeof ServicesOfficeCommercialCleaningRoute
  ServicesResidentialWireHouseCleaningRoute: typeof ServicesResidentialWireHouseCleaningRoute
  ServicesTreeBrushRemovalRoute: typeof ServicesTreeBrushRemovalRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCustomBuiltStormSheltersRoute: ServicesCustomBuiltStormSheltersRoute,
  ServicesGravelDirtWorkRoute: ServicesGravelDirtWorkRoute,
  ServicesInGroundPrefabricatedStormSheltersRoute:
    ServicesInGroundPrefabricatedStormSheltersRoute,
  ServicesLandscapingRoute: ServicesLandscapingRoute,
  ServicesLawnMowingRoute: ServicesLawnMowingRoute,
  ServicesOfficeCommercialCleaningRoute: ServicesOfficeCommercialCleaningRoute,
  ServicesResidentialWireHouseCleaningRoute:
    ServicesResidentialWireHouseCleaningRoute,
  ServicesTreeBrushRemovalRoute: ServicesTreeBrushRemovalRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FreeQuoteRoute: FreeQuoteRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
